traffic schema
Tan4ek/get-your-vpn-config pull request #3
Opened 2022-04-17 07:11 UTC by Tan4ek

2022-04-18 18:49 UTC, TimAle requested changes
`persistant.py` -> `persistent.py`

2022-04-18 18:49 UTC, TimAle commented on migrations/versions/2022-04-16_56001dbb442e_traffic_model.py
> +    op.create_table('traffic_record',
make all the table names plural if these names relate to a single row content

2022-04-18 18:49 UTC, TimAle commented on migrations/versions/2022-04-16_56001dbb442e_traffic_model.py
> +    op.create_index(op.f('ix_provider_external_id'), 'provider', ['external_id'], unique=True)
probably `idx_provider_external_id`

2022-04-18 18:49 UTC, TimAle commented on migrations/versions/2022-04-16_56001dbb442e_traffic_model.py
> +    op.execute("UPDATE provider SET external_id = substr(payload,20,36) WHERE type='openvpn'")
nasty boy!

2022-04-18 18:49 UTC, TimAle commented on repository/persistant.py
> +    date_to = Column("date_to", Integer, nullable=False)
any chances we can have it as a date?

2022-04-18 18:49 UTC, TimAle commented on repository/persistant.py
> +                        payload: str) -> VpnProviderEntity:
looks like this method should create not a VPN provider only, but a provider in general

2022-04-18 19:54 UTC, Tan4ek commented on migrations/versions/2022-04-16_56001dbb442e_traffic_model.py
> +    op.create_table('traffic_record',
Thanks, renamed ✅

2022-04-18 19:54 UTC, Tan4ek commented on migrations/versions/2022-04-16_56001dbb442e_traffic_model.py
> +    op.execute("UPDATE provider SET external_id = substr(payload,20,36) WHERE type='openvpn'")
🤷‍♂️

2022-04-18 19:54 UTC, Tan4ek commented on migrations/versions/2022-04-16_56001dbb442e_traffic_model.py
> +    op.create_index(op.f('ix_provider_external_id'), 'provider', ['external_id'], unique=True)
Thanks ✅

2022-04-18 19:54 UTC, Tan4ek commented on repository/persistant.py
> +    date_to = Column("date_to", Integer, nullable=False)
No, sqlite doesn't have native date data type https://www.sqlite.org/datatype3.html#date_and_time_datatype . Here I use integer approach

2022-04-18 19:54 UTC, Tan4ek commented on repository/persistant.py
> +                        payload: str) -> VpnProviderEntity:
Project name is 'get-your-vpn', so I've decided to use vpn in naming to )

2022-04-19 08:25 UTC, TimAle approved these changes

2022-05-09 14:52 UTC, merged